apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic-server
  template:
    metadata:
      labels:
        app: mautic-server
    spec:
      containers:
      - env:
        - name: MAUTIC_DB_HOST
          value: platform-shared-prod-mysql.cluster-cdszszzxdtq9.ap-south-1.rds.amazonaws.com
        - name: MAUTIC_DB_PORT
          value: "3306"
        - name: MAUTIC_DB_DATABASE
          value: mautic
        - name: MAUTIC_DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: coderstrust-em-mautic-mysql-secret
        - name: MAUTIC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: coderstrust-em-mautic-mysql-secret
        - name: MAUTIC_URL
          value: https://mt.coderstrust.global
        - name: MAUTIC_MESSENGER_DSN_EMAIL
          value: doctrine://default
        - name: MAUTIC_MESSENGER_DSN_HIT
          value: doctrine://default
        envFrom:
        - configMapRef:
            name: mautic-config
        - secretRef:
            name: mautic-secret
        image: docker.io/tanjim/mautic:web@sha256:a561cfec3f3348dbffb15f1099e34e935c5acc1ced1008a75edf7b9d374b94d9
        name: mautic-server
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/www/html/var/logs
          name: logs
        - mountPath: /var/www/html/docroot/media/files
          name: files
        - mountPath: /var/www/html/docroot/media/images
          name: images
        - mountPath: /var/www/html/config
          name: config
        - mountPath: /var/www/html/docroot/var/tmp
          name: tmp
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: mautic-logs
      - name: files
        persistentVolumeClaim:
          claimName: mautic-files
      - name: images
        persistentVolumeClaim:
          claimName: mautic-images
      - name: config
        persistentVolumeClaim:
          claimName: mautic-config
      - name: tmp
        persistentVolumeClaim:
          claimName: mautic-tmp