apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mautic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mautic.image.repository }}:web-{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          envFrom:
            # DB ConfigMap
            {{- if .Values.mautic.db.existingConfigMap }}
            - configMapRef:
                name: {{ .Values.mautic.db.existingConfigMap }}
            {{- else }} 
            - configMapRef:
                name: {{ include "mautic.fullname" . }}-db
            {{- end }}
            # DB Secret
            {{- if .Values.mautic.db.existingSecret }}
            - secretRef:
                name: {{ .Value.mautic.db.existingSecret }}
            {{- else }}
            - secretRef:
                name: {{ include "mautic.fullname" . }}-db
            {{- end }}
            # Maustic ConfigMap
            {{- if .Values.mautic.existingConfigMap }}
            - configMapRef:
                name: {{ .Values.mautic.existingConfigMap }}
            {{- else }}
            - configMapRef:
                name: {{ include "mautic.fullname" . }}-config
            {{- end }}
            # Mautic Secret
            {{- if .Values.mautic.existingSecret }}
            - secretRef:
                name: {{ .Values.mautic.existingSecret }}
            {{- else }}
            - secretRef:
                name: {{ include "mautic.fullname" . }}-secret
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   {{- toYaml .Values.livenessProbe | nindent 12 }}
          # readinessProbe:
          #   {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.mautic.web.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /var/www/html/var/logs
              name: logs
            - mountPath: /var/www/html/docroot/media/files
              name: files
            - mountPath: /var/www/html/docroot/media/images
              name: images
            - mountPath: /var/www/html/config
              name: config
            - mountPath: /var/www/html/docroot/var/tmp
              name: tmp
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "mautic.fullname" . }}-logs
        - name: files
          persistentVolumeClaim:
            claimName: {{ include "mautic.fullname" . }}-files
        - name: images
          persistentVolumeClaim:
            claimName: {{ include "mautic.fullname" . }}-images
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "mautic.fullname" . }}-config
        - name: tmp
          persistentVolumeClaim:
            claimName: {{ include "mautic.fullname" . }}-tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
