{{- if not .Values.mautic.mysql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}-mysql
type: Opaque
data:
  {{- if .Values.mautic.mysql.auth.user }}
  MAUTIC_DB_USER: {{ .Values.mautic.mysql.auth.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.mautic.mysql.auth.password }}
  MAUTIC_DB_PASSWORD: {{ .Values.mautic.mysql.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mautic.mysql.auth.database }}
  MAUTIC_DB_DATABASE: {{ .Values.mautic.mysql.auth.database | b64enc | quote }}
  {{- end }}
{{- end }}
