{{- if not .Values.mautic.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}-db
type: Opaque
data:
{{- toYaml .Values.mautic.db.secret | nindent 2 }}
{{- end }}
---
{{- if not .Values.mautic.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}-secret
type: Opaque
data:
{{- toYaml .Values.mautic.secret | nindent 2 }}
{{- end }}